"""
Blog Management System
Generated by PPPL Model Compiler
"""


# Import from library
from library.User import User
from library.Post import Post
from library.Comment import Comment
from library.Category import Category


def main():
    """Main entry point"""
    print("="*60)
    print("Blog Management System")
    print("="*60)
    print("")


    # Initialize system components
    print("Initializing active classes with state machines...")
    print("")
    print("Creating Post...")
    post = Post()
    print(f"  Status: {post.Status.value}")
    print("")
    # Demo: Trigger some state transitions
    print("Testing state transitions...")
    print("")
    print('Triggering event: publish')
    post.handle_event('publish')
    print("System running successfully!")
    print("All state machines are operational.")


def demonstrate_workflow():
    """Demonstrate complete system workflow"""
    print("\n" + "="*60)
    print("WORKFLOW DEMONSTRATION")
    print("="*60 + "\n")

    print("1. Creating User instance...")
    obj = User()
    print(f"   Created: {obj}")
    print("")
    print("3. Validating instance...")
    if obj.validate():
        print("   ✓ Validation passed")
    else:
        print("   ✗ Validation failed")
    print("")
    print("4. Serializing to dictionary...")
    data = obj.to_dict()
    print(f"   Keys: {list(data.keys())}")
    print("")
    print("="*60)
    print("Workflow demonstration complete!")
    print("="*60)


    # Run workflow demonstration
    demonstrate_workflow()


if __name__ == "__main__":
    main()