"""
Banking System
Generated by PPPL Model Compiler
"""


# Import from library
from library.Account import Account
from library.Transaction import Transaction
from library.Customer import Customer


def main():
    """Main entry point"""
    print("="*60)
    print("Banking System")
    print("="*60)
    print("")


    # Initialize system components
    print("Initializing active classes with state machines...")
    print("")
    print("Creating Account...")
    account = Account()
    print(f"  Status: {account.Status.value}")
    print("")
    print("Creating Transaction...")
    transaction = Transaction()
    print(f"  Status: {transaction.Status.value}")
    print("")
    # Demo: Trigger some state transitions
    print("Testing state transitions...")
    print("")
    print('Triggering event: approve')
    account.handle_event('approve')
    print("System running successfully!")
    print("All state machines are operational.")


def demonstrate_workflow():
    """Demonstrate complete system workflow"""
    print("\n" + "="*60)
    print("WORKFLOW DEMONSTRATION")
    print("="*60 + "\n")

    print("1. Creating Account instance...")
    obj = Account()
    print(f"   Created: {obj}")
    print("")
    print("2. Triggering state transitions...")
    print(f"   {i}. Triggering: approve")
    obj.approve()
    print(f"      Status: {obj.Status.value}")
    print(f"   {i}. Triggering: freeze")
    obj.freeze()
    print(f"      Status: {obj.Status.value}")
    print(f"   {i}. Triggering: unfreeze")
    obj.unfreeze()
    print(f"      Status: {obj.Status.value}")
    print("")
    print("3. Validating instance...")
    if obj.validate():
        print("   ✓ Validation passed")
    else:
        print("   ✗ Validation failed")
    print("")
    print("4. Serializing to dictionary...")
    data = obj.to_dict()
    print(f"   Keys: {list(data.keys())}")
    print("")
    print("="*60)
    print("Workflow demonstration complete!")
    print("="*60)


    # Run workflow demonstration
    demonstrate_workflow()


if __name__ == "__main__":
    main()