from .code_generator import CodeGenerator
from typing import Dict

class JavaGenerator(CodeGenerator):
    """Generate Java code from PPPL model"""
    
    def get_file_extension(self) -> str:
        return ".java"
    
    def generate_class(self, class_data: Dict, domain: str) -> str:
        """Generate Java class code"""
        class_name = class_data['name']
        description = class_data.get('description', '')
        attributes = class_data.get('attributes', [])
        
        code = []
        
        # Package declaration
        package_name = domain.lower().replace(' ', '_')
        code.append(f"package {package_name};")
        code.append("\n")
        
        # Imports
        code.append("import java.util.UUID;")
        code.append("import java.time.LocalDateTime;")
        code.append("\n")
        
        # Class declaration
        code.append(f"/**")
        code.append(f" * {description}")
        code.append(f" */")
        code.append(f"public class {class_name} {{")
        code.append("\n")
        
        # Generate attributes
        for attr in attributes:
            attr_code = self._generate_attribute(attr)
            code.append(f"    {attr_code}")
        
        code.append("\n")
        
        # Constructor
        code.append(f"    public {class_name}() {{")
        code.append("        // Constructor")
        code.append("    }")
        code.append("\n")
        
        # Getters and setters
        for attr in attributes:
            code.append(self._generate_getter_setter(attr))
        
        code.append("}")
        
        return "\n".join(code)
    
    def _generate_attribute(self, attr: Dict) -> str:
        """Generate attribute code"""
        name = attr['name']
        data_type = attr['data_type']
        
        # Map PPPL types to Java types
        type_mapping = {
            'string': 'String',
            'integer': 'int',
            'float': 'double',
            'boolean': 'boolean',
            'datetime': 'LocalDateTime',
            'uuid': 'UUID',
            'state': 'String'
        }
        
        java_type = type_mapping.get(data_type, 'String')
        return f"private {java_type} {name};"
    
    def _generate_getter_setter(self, attr: Dict) -> str:
        """Generate getter and setter methods"""
        name = attr['name']
        data_type = attr['data_type']
        
        type_mapping = {
            'string': 'String',
            'integer': 'int',
            'float': 'double',
            'boolean': 'boolean',
            'datetime': 'LocalDateTime',
            'uuid': 'UUID',
            'state': 'String'
        }
        
        java_type = type_mapping.get(data_type, 'String')
        
        code = []
        code.append(f"    public {java_type} get{name}() {{")
        code.append(f"        return {name};")
        code.append("    }")
        code.append("\n")
        code.append(f"    public void set{name}({java_type} {name}) {{")
        code.append(f"        this.{name} = {name};")
        code.append("    }")
        code.append("\n")
        
        return "\n".join(code)
    
    def generate_state_machine(self, state_machine: Dict, class_name: str) -> str:
        """Generate state machine code"""
        return "// State machine to be implemented"
    
    def generate_relationship(self, relationship: Dict) -> str:
        """Generate relationship code"""
        return "// Relationship implementation"
    
    def generate_main_file(self, parser) -> str:
        """Generate Main.java entry point"""
        code = []
        
        system_name = parser.model.get('system_name', 'System')
        
        # Import statements
        for domain in parser.get_domains():
            package_name = domain['name'].lower().replace(' ', '_')
            code.append(f"import library.{package_name}.*;")
        
        code.append("\n")
        code.append("/**")
        code.append(f" * {system_name}")
        code.append(" * Generated by PPPL Model Compiler")
        code.append(" */")
        code.append("public class Main {")
        code.append("    public static void main(String[] args) {")
        code.append(f'        System.out.println("{"="*60}");')
        code.append(f'        System.out.println("{system_name}");')
        code.append(f'        System.out.println("{"="*60}");')
        code.append('        System.out.println("");')
        code.append("\n")
        code.append("        // Initialize system components")
        code.append('        System.out.println("System initialized successfully!");')
        code.append("    }")
        code.append("}")
        
        return "\n".join(code)
